M48
; DRILL file {KiCad 7.0.9} date Mon Jan  1 16:10:20 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-01T16:10:20+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X68.0Y-30.0
X68.0Y-150.0
X128.0Y-30.0
X128.0Y-150.0
X188.0Y-30.0
X188.0Y-150.0
T0
M30
